### ISSUE TITLE
Change url to webjcs

### ISSUE THREAD

**Issue by daniel-j** [soulweaver91/project-carrot-website#3]
The project you link to is a not working version of WebJCS, it's my 2.0 rewrite in-suspended-development repo.

You should link to the current download on J2O instead: https://www.jazz2online.com/downloads/6796/webjcs/

It's probably broken nowadays though :/

_\- djazz -_

**Comment by soulweaver91** [comment]
Oh, my bad; seems I assumed too much without actually checking the contents of that repo properly. Will fix, thanks for reporting!
